### ISSUE TITLE
Hovering on a first-level type definition shows the type twice

### ISSUE THREAD

**Issue by busybox11** [mylesmmurphy/prettify-ts#4] opened 2023-12-30 04:00 UTC
As the title says, whenever I hover a "first-level" type (a type without any extension or anything - just the type itself), I have its definition shown twice in VSCode's popup, one from the already existing TS features, one from this extension.

![image](https://github.com/mylesmmurphy/prettify-ts/assets/29630035/aaeffea8-4f54-4d8b-b6b3-c4d9e0c5c676)

Could it be possible to hide either one of them when this happens? The initial TS features can show useful type info outside of this case, so I don't think it's a good idea to remove them altogether.

What do you think about it?

(Also, the tab padding isn't the same as the rest of the already existing TS features uses. For the sake of consistency, could it be a good idea to standardize it? This is only a suggestion though)

**Comment by busybox11** [comment] 2023-12-30 23:16
Weird, it also seem to have conflicting type results..
Haven't had the time to look into it. Figured it would be worth to mention it here, just in case.

![image](https://github.com/mylesmmurphy/prettify-ts/assets/29630035/dc194144-06f3-4c2b-beb6-8fc6f367ffab)

**Comment by mylesmmurphy** [comment] 2023-12-31 02:30
Hey @busybox11! Thanks for bringing this to my attention. I am currently in the process of exploring options for optimizing the extension, in which I can probably include checks to make sure we're not displaying information that isn't helpful.

I will look into the incorrect typing as well on the array. Are you able to send a code snippet I can debug off of by any chance? Thanks again :)

**Comment by mylesmmurphy** [comment] 2023-12-31 20:42
Hi @busybox11 
Wanted to update you, I've got some working changes which implement your feedback, with a PR here: https://github.com/mylesmmurphy/prettify-ts/pull/5

Going to be thoroughly testing these changes now, but should hopefully be merged and released in the next couple of days!

**Comment by mylesmmurphy** [comment] 2024-01-01 18:12
Just released v0.0.14, which covers all of the feedback here. Thanks again for your thoughts! Please try out the latest version, and please don't hesitate to send more feedback if you have any!

**Closed by mylesmmurphy** 2024-01-01 18:12 UTC

**Comment by busybox11** [comment] 2024-01-02 21:00
Hi!
Apologies for the late response. Had a pretty busy week.
I continued to use the extension the last couple of days and it has been working great!

I'm really glad to see your updates, I'm going to check this out soon and I'll get you updated on that.
Same goes for the code snippet. I'll try to reproduce it, though unfortunately those were stale changes that have been modified since, and unfortunately I didn't save that state of the code.

Thanks again! Also happy new year :)

**Comment by mylesmmurphy** [comment] 2024-01-02 21:39
No problems at all! Really happy to hear the extension is working as expected.

In an older version, users reported seeing the "any" type show up because I hadn't set up the extension to use the user's tsconfig. A PR was created to fix this issue by finding and using the a tsconfig file, but it wasn't set up to work with a monorepo.

The most recent version of the extension now will work correctly with monorepos or non-standard locations for tsconfigs, so I'm hoping that resolves your issue. 🤞 Please let me know if you're still able to reproduce or seeing any other issues and I'd be happy to work on a fix!

Happy new year to you as well 🥳
