### ISSUE TITLE
No longer seems to work with the latest Typescript (5.6.3)

### ISSUE THREAD

**Issue by LoiLock** [mylesmmurphy/prettify-ts#42] opened 2024-10-10 12:34 UTC
Following the example provided in the screenshot:

<img width="162" alt="image" src="https://github.com/user-attachments/assets/8d50ba28-7f07-4187-9b43-676c256eaed6">

<img width="579" alt="image" src="https://github.com/user-attachments/assets/3eac11ad-90a7-4b48-b07f-3b5a75288e12">

In the past this worked without fail, and had been enjoying it for a long time

**Comment by LoiLock** [comment] 2024-10-10 13:02
Downgrading to 0.019 Works for me, but I don't see that as a solution

**Comment by mylesmmurphy** [comment] 2024-10-11 18:16
Hey @LoiLock 
Thanks for mentioning this. I'm unfortunately unable to reproduce this. I have tried using the published version (v0.1.5), with the most recent versions of TypeScript (5.6.3, 5.7.0-dev.20241010, 5.7.0-dev.20241011). Would you mind sharing your version of VSCode and TypeScript which you're running into this? 🙏

**Comment by LoiLock** [comment] 2024-10-12 10:52
Vscode 1.94.1 and I'm using my workspace's Typescript binary, which is 5.6.3. It's strange, I noticed it a while ago but didn't initially do anything about it, I unfortunately can't share the project itself since it's for the company I work for, so creating a minimal reproduction would be difficult. I don't know if it's relevant that we use pnpm (which is also how typescript is installed in our project).

My node version is 22.8.0, installed using nvm.

I'm sorry that I can't be of any more help, 0.1.6 has been working beautifully for me, and it's easily my favorite extension!

**Comment by mylesmmurphy** [comment] 2024-11-11 04:12
Hey @LoiLock! I'm going to close this for now, but please feel free to re-open if you run into the issue again. 😄

**Closed by mylesmmurphy** 2024-11-11 04:12 UTC
